// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddUser'](arg1, arg2, arg3);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function EditUser(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditUser'](arg1, arg2, arg3, arg4);
}

export function GeneratePassword() {
  return window['go']['main']['App']['GeneratePassword']();
}

export function ListUsers() {
  return window['go']['main']['App']['ListUsers']();
}
